//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DIS_Entities : DbContext
    {
        public DIS_Entities()
            : base("name=DIS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ph_assignments> ph_assignments { get; set; }
        public DbSet<ph_assignmentshistory> ph_assignmentshistory { get; set; }
        public DbSet<ph_attestations> ph_attestations { get; set; }
        public DbSet<ph_diplomdata> ph_diplomdata { get; set; }
        public DbSet<ph_events> ph_events { get; set; }
        public DbSet<ph_eventtypes> ph_eventtypes { get; set; }
        public DbSet<ph_exams> ph_exams { get; set; }
        public DbSet<ph_examtypes> ph_examtypes { get; set; }
        public DbSet<ph_individualplans> ph_individualplans { get; set; }
        public DbSet<ph_reports> ph_reports { get; set; }
        public DbSet<ph_topics> ph_topics { get; set; }
        public DbSet<ph_topicshistory> ph_topicshistory { get; set; }
        public DbSet<ph_tutornames> ph_tutornames { get; set; }
        public DbSet<ph_tutors> ph_tutors { get; set; }
        public DbSet<un_acceptancereasons> un_acceptancereasons { get; set; }
        public DbSet<un_assignments> un_assignments { get; set; }
        public DbSet<un_assignmentspermanent> un_assignmentspermanent { get; set; }
        public DbSet<un_assignmentstemporary> un_assignmentstemporary { get; set; }
        public DbSet<un_basicclasses> un_basicclasses { get; set; }
        public DbSet<un_binaryfiles> un_binaryfiles { get; set; }
        public DbSet<un_cities> un_cities { get; set; }
        public DbSet<un_citizenship> un_citizenship { get; set; }
        public DbSet<un_contactdata> un_contactdata { get; set; }
        public DbSet<un_contacttypes> un_contacttypes { get; set; }
        public DbSet<un_countries> un_countries { get; set; }
        public DbSet<un_departments> un_departments { get; set; }
        public DbSet<un_departmentshistory> un_departmentshistory { get; set; }
        public DbSet<un_departmenttree> un_departmenttree { get; set; }
        public DbSet<un_departmenttypes> un_departmenttypes { get; set; }
        public DbSet<un_educationdurations> un_educationdurations { get; set; }
        public DbSet<un_educationforms> un_educationforms { get; set; }
        public DbSet<un_educationlevels> un_educationlevels { get; set; }
        public DbSet<un_egntypes> un_egntypes { get; set; }
        public DbSet<un_ekatte> un_ekatte { get; set; }
        public DbSet<un_filetypes> un_filetypes { get; set; }
        public DbSet<un_gender> un_gender { get; set; }
        public DbSet<un_healthinsuranse> un_healthinsuranse { get; set; }
        public DbSet<un_identitycards> un_identitycards { get; set; }
        public DbSet<un_identitycardshistory> un_identitycardshistory { get; set; }
        public DbSet<un_languagelevels> un_languagelevels { get; set; }
        public DbSet<un_languages> un_languages { get; set; }
        public DbSet<un_messages> un_messages { get; set; }
        public DbSet<un_municipalities> un_municipalities { get; set; }
        public DbSet<un_nsicodes> un_nsicodes { get; set; }
        public DbSet<un_organisation> un_organisation { get; set; }
        public DbSet<un_personlanguages> un_personlanguages { get; set; }
        public DbSet<un_persons> un_persons { get; set; }
        public DbSet<un_personshistory> un_personshistory { get; set; }
        public DbSet<un_positions> un_positions { get; set; }
        public DbSet<un_positiontypes> un_positiontypes { get; set; }
        public DbSet<un_professionalareas> un_professionalareas { get; set; }
        public DbSet<un_professionalgroups> un_professionalgroups { get; set; }
        public DbSet<un_regions> un_regions { get; set; }
        public DbSet<un_roles> un_roles { get; set; }
        public DbSet<un_sciencehistory> un_sciencehistory { get; set; }
        public DbSet<un_specialities> un_specialities { get; set; }
        public DbSet<un_specialitytypes> un_specialitytypes { get; set; }
        public DbSet<un_statuses> un_statuses { get; set; }
        public DbSet<un_studytypes> un_studytypes { get; set; }
        public DbSet<un_treerevisions> un_treerevisions { get; set; }
        public DbSet<un_userrights> un_userrights { get; set; }
        public DbSet<un_users> un_users { get; set; }
    }
}
