//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_assignmentshistory
    {
        public int id_phdAssignment { get; set; }
        public int id_person { get; set; }
        public int id_department { get; set; }
        public int id_professionalGroup { get; set; }
        public string PhdCode { get; set; }
        public Nullable<int> StartOrderNumber { get; set; }
        public Nullable<System.DateTime> StartOrderDate { get; set; }
        public Nullable<System.DateTime> EndOrderDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> UseDormitory { get; set; }
        public Nullable<bool> UseScholarship { get; set; }
        public int id_status { get; set; }
        public int id_userEdit { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> id_module { get; set; }
        public int id_studyType { get; set; }
        public int id_basicClass { get; set; }
        public int id_nsiCode { get; set; }
        public int id_acceptanceReason { get; set; }
        public int id_educationDuration { get; set; }
        public int id_educationForm { get; set; }
        public int id_phdAssignmentParent { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
    
        public virtual un_professionalgroups un_professionalgroups { get; set; }
        public virtual un_departmenttree un_departmenttree { get; set; }
        public virtual un_statuses un_statuses { get; set; }
        public virtual un_studytypes un_studytypes { get; set; }
    }
}
