//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_assignments
    {
        public ph_assignments()
        {
            this.ph_attestations = new HashSet<ph_attestations>();
            this.ph_diplomdata = new HashSet<ph_diplomdata>();
            this.ph_events = new HashSet<ph_events>();
            this.ph_exams = new HashSet<ph_exams>();
            this.ph_individualplans = new HashSet<ph_individualplans>();
            this.ph_topicshistory = new HashSet<ph_topicshistory>();
            this.ph_topics = new HashSet<ph_topics>();
            this.ph_tutors = new HashSet<ph_tutors>();
            this.ph_reports = new HashSet<ph_reports>();
        }
    
        public int id_phdAssignment { get; set; }
        public int id_person { get; set; }
        public Nullable<int> id_speciality { get; set; }
        public string PhdCode { get; set; }
        public string StartOrderNumber { get; set; }
        public Nullable<System.DateTime> StartOrderDate { get; set; }
        public string EndOrderNumber { get; set; }
        public Nullable<System.DateTime> EndOrderDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> UseDormitory { get; set; }
        public Nullable<bool> UseScholarship { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_module { get; set; }
        public Nullable<int> id_studyType { get; set; }
        public Nullable<int> id_basicClass { get; set; }
        public Nullable<int> id_nsiCode { get; set; }
        public Nullable<int> id_acceptanceReason { get; set; }
        public Nullable<int> id_educationDuration { get; set; }
        public Nullable<int> id_educationForm { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> id_department { get; set; }
        public Nullable<int> id_mastertype { get; set; }
        public Nullable<bool> UseHolidayFacilities { get; set; }
        public Nullable<bool> ParticipatedIntProgs { get; set; }
        public Nullable<bool> TuProvidesHI { get; set; }
    
        public virtual un_specialities un_specialities { get; set; }
        public virtual un_acceptancereasons un_acceptancereasons { get; set; }
        public virtual un_departments un_departments { get; set; }
        public virtual un_nsicodes un_nsicodes { get; set; }
        public virtual un_statuses un_statuses { get; set; }
        public virtual un_studytypes un_studytypes { get; set; }
        public virtual un_educationdurations un_educationdurations { get; set; }
        public virtual un_educationforms un_educationforms { get; set; }
        public virtual ICollection<ph_attestations> ph_attestations { get; set; }
        public virtual ICollection<ph_diplomdata> ph_diplomdata { get; set; }
        public virtual ICollection<ph_events> ph_events { get; set; }
        public virtual ICollection<ph_exams> ph_exams { get; set; }
        public virtual ICollection<ph_individualplans> ph_individualplans { get; set; }
        public virtual ICollection<ph_topicshistory> ph_topicshistory { get; set; }
        public virtual ICollection<ph_topics> ph_topics { get; set; }
        public virtual ICollection<ph_tutors> ph_tutors { get; set; }
        public virtual ICollection<ph_reports> ph_reports { get; set; }
    }
}
