//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_diplomdata
    {
        public int id_diplomData { get; set; }
        public string LastEducationUniversity { get; set; }
        public string LastEducationSubject { get; set; }
        public string LastEducationEndYear { get; set; }
        public string LastDiplomNumber { get; set; }
        public Nullable<System.DateTime> LastDiplomDate { get; set; }
        public Nullable<int> id_citiesLastEducation { get; set; }
        public Nullable<int> id_educationLast { get; set; }
        public int id_pdhAssignment { get; set; }
        public Nullable<int> id_countryLastEducation { get; set; }
    
        public virtual ph_assignments ph_assignments { get; set; }
        public virtual un_cities un_cities { get; set; }
        public virtual un_educationlevels un_educationlevels { get; set; }
    }
}
