//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_examtypes
    {
        public ph_examtypes()
        {
            this.ph_exams = new HashSet<ph_exams>();
        }
    
        public int id_examType { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public Nullable<int> id_binaryFile { get; set; }
    
        public virtual ICollection<ph_exams> ph_exams { get; set; }
    }
}
