//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_exams
    {
        public int id_exam { get; set; }
        public string Name { get; set; }
        public int id_examType { get; set; }
        public int id_phAssignment { get; set; }
        public double Mark { get; set; }
        public Nullable<int> id_examinator1 { get; set; }
        public Nullable<int> id_examinator2 { get; set; }
        public Nullable<int> id_examinator3 { get; set; }
        public System.DateTime Date { get; set; }
        public string MarkName { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual ph_assignments ph_assignments { get; set; }
        public virtual ph_examtypes ph_examtypes { get; set; }
    }
}
