//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_tutornames
    {
        public ph_tutornames()
        {
            this.ph_tutors = new HashSet<ph_tutors>();
        }
    
        public int id_tutorName { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ph_tutors> ph_tutors { get; set; }
    }
}
