//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_assignments
    {
        public int id_assignment { get; set; }
        public int id_person { get; set; }
        public int id_department { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public int id_position { get; set; }
        public Nullable<int> id_positionType { get; set; }
    
        public virtual un_departments un_departments { get; set; }
        public virtual un_persons un_persons { get; set; }
        public virtual un_positions un_positions { get; set; }
    }
}
