//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_binaryfiles
    {
        public un_binaryfiles()
        {
            this.ph_attestations = new HashSet<ph_attestations>();
            this.ph_individualplans = new HashSet<ph_individualplans>();
            this.ph_reports = new HashSet<ph_reports>();
        }
    
        public int id_binaryFile { get; set; }
        public string Name { get; set; }
        public int id_fileType { get; set; }
        public byte[] Binary { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual ICollection<ph_attestations> ph_attestations { get; set; }
        public virtual ICollection<ph_individualplans> ph_individualplans { get; set; }
        public virtual ICollection<ph_reports> ph_reports { get; set; }
        public virtual un_filetypes un_filetypes { get; set; }
    }
}
