//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_contactdata
    {
        public int id_contactdata { get; set; }
        public string Address { get; set; }
        public Nullable<int> id_city { get; set; }
        public string email { get; set; }
        public int id_person { get; set; }
        public string Phone { get; set; }
        public string Room { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_module { get; set; }
        public Nullable<int> id_contactType { get; set; }
    
        public virtual un_cities un_cities { get; set; }
        public virtual un_contacttypes un_contacttypes { get; set; }
        public virtual un_persons un_persons { get; set; }
    }
}
