//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_cities
    {
        public un_cities()
        {
            this.ph_diplomdata = new HashSet<ph_diplomdata>();
            this.un_contactdata = new HashSet<un_contactdata>();
            this.un_identitycards = new HashSet<un_identitycards>();
            this.un_identitycardshistory = new HashSet<un_identitycardshistory>();
            this.un_identitycards1 = new HashSet<un_identitycards>();
            this.un_identitycardshistory1 = new HashSet<un_identitycardshistory>();
        }
    
        public int id_city { get; set; }
        public Nullable<int> id_ekatte { get; set; }
        public string Name { get; set; }
        public string Municipality { get; set; }
        public string Region { get; set; }
        public string Type { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> id_country { get; set; }
        public Nullable<int> id_municipality { get; set; }
    
        public virtual ICollection<ph_diplomdata> ph_diplomdata { get; set; }
        public virtual un_countries un_countries { get; set; }
        public virtual un_ekatte un_ekatte { get; set; }
        public virtual un_municipalities un_municipalities { get; set; }
        public virtual ICollection<un_contactdata> un_contactdata { get; set; }
        public virtual ICollection<un_identitycards> un_identitycards { get; set; }
        public virtual ICollection<un_identitycardshistory> un_identitycardshistory { get; set; }
        public virtual ICollection<un_identitycards> un_identitycards1 { get; set; }
        public virtual ICollection<un_identitycardshistory> un_identitycardshistory1 { get; set; }
    }
}
