//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_countries
    {
        public un_countries()
        {
            this.un_cities = new HashSet<un_cities>();
            this.un_citizenship = new HashSet<un_citizenship>();
        }
    
        public int id_country { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public string Code { get; set; }
        public string TelCode { get; set; }
        public Nullable<bool> IsCity { get; set; }
        public string ISO_3166Code { get; set; }
        public string ISO_A3 { get; set; }
        public string ISO_Number { get; set; }
        public bool IsEUMember { get; set; }
    
        public virtual ICollection<un_cities> un_cities { get; set; }
        public virtual ICollection<un_citizenship> un_citizenship { get; set; }
    }
}
