//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_contacttypes
    {
        public un_contacttypes()
        {
            this.un_contactdata = new HashSet<un_contactdata>();
        }
    
        public int id_contactType { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    
        public virtual ICollection<un_contactdata> un_contactdata { get; set; }
    }
}
