//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_citizenship
    {
        public un_citizenship()
        {
            this.un_identitycards = new HashSet<un_identitycards>();
        }
    
        public int id_citizenship { get; set; }
        public int id_country { get; set; }
        public int id_person { get; set; }
    
        public virtual un_countries un_countries { get; set; }
        public virtual un_persons un_persons { get; set; }
        public virtual ICollection<un_identitycards> un_identitycards { get; set; }
    }
}
