//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_departmentshistory
    {
        public int id_department { get; set; }
        public int id_EKATTE { get; set; }
        public string Address { get; set; }
        public string BULSTAT { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public string NameShort { get; set; }
        public int id_departmentType { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_module { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public int id_departmentParent { get; set; }
    
        public virtual un_departments un_departments { get; set; }
        public virtual un_departmenttypes un_departmenttypes { get; set; }
    }
}
