//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_departmenttree
    {
        public un_departmenttree()
        {
            this.ph_assignmentshistory = new HashSet<ph_assignmentshistory>();
            this.un_departmenttree1 = new HashSet<un_departmenttree>();
        }
    
        public int id_departmentTree { get; set; }
        public Nullable<int> id_departmentParent { get; set; }
        public int id_treeRevision { get; set; }
        public int id_department { get; set; }
        public int Code { get; set; }
    
        public virtual ICollection<ph_assignmentshistory> ph_assignmentshistory { get; set; }
        public virtual un_departments un_departments { get; set; }
        public virtual ICollection<un_departmenttree> un_departmenttree1 { get; set; }
        public virtual un_departmenttree un_departmenttree2 { get; set; }
        public virtual un_treerevisions un_treerevisions { get; set; }
    }
}
