//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_departmenttypes
    {
        public un_departmenttypes()
        {
            this.un_departments = new HashSet<un_departments>();
            this.un_departmentshistory = new HashSet<un_departmentshistory>();
        }
    
        public int id_departmentType { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<un_departments> un_departments { get; set; }
        public virtual ICollection<un_departmentshistory> un_departmentshistory { get; set; }
    }
}
