//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_educationlevels
    {
        public un_educationlevels()
        {
            this.ph_diplomdata = new HashSet<ph_diplomdata>();
            this.un_sciencehistory = new HashSet<un_sciencehistory>();
        }
    
        public int id_educationLevel { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ph_diplomdata> ph_diplomdata { get; set; }
        public virtual ICollection<un_sciencehistory> un_sciencehistory { get; set; }
    }
}
