//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_ekatte
    {
        public un_ekatte()
        {
            this.un_cities = new HashSet<un_cities>();
        }
    
        public int id_ekatte { get; set; }
        public string Name { get; set; }
        public string Municipality { get; set; }
        public string Region { get; set; }
        public string Code { get; set; }
        public Nullable<int> id_municipality { get; set; }
    
        public virtual ICollection<un_cities> un_cities { get; set; }
        public virtual un_municipalities un_municipalities { get; set; }
    }
}
