//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_languagelevels
    {
        public un_languagelevels()
        {
            this.un_personlanguages = new HashSet<un_personlanguages>();
        }
    
        public int id_languageLevel { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<un_personlanguages> un_personlanguages { get; set; }
    }
}
