//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_municipalities
    {
        public un_municipalities()
        {
            this.un_cities = new HashSet<un_cities>();
            this.un_ekatte = new HashSet<un_ekatte>();
        }
    
        public int id_municipality { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> id_region { get; set; }
    
        public virtual ICollection<un_cities> un_cities { get; set; }
        public virtual ICollection<un_ekatte> un_ekatte { get; set; }
        public virtual un_regions un_regions { get; set; }
    }
}
