//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_organisation
    {
        public int id_organisation { get; set; }
        public int MOMNCode { get; set; }
        public int Year { get; set; }
        public int Period { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public int BasicSchoolType { get; set; }
        public int SchoolType { get; set; }
        public int BudgetFrom { get; set; }
        public int id_EKTATTE { get; set; }
        public int PostalCode { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Phone4 { get; set; }
        public string Phone5 { get; set; }
        public string Fax { get; set; }
        public string email { get; set; }
        public string WebAddress { get; set; }
        public string Bulstat { get; set; }
        public string FoundationYear { get; set; }
    }
}
