//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_positions
    {
        public un_positions()
        {
            this.un_assignments = new HashSet<un_assignments>();
        }
    
        public int id_poistion { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_role { get; set; }
        public int id_positionType { get; set; }
    
        public virtual ICollection<un_assignments> un_assignments { get; set; }
        public virtual un_positiontypes un_positiontypes { get; set; }
        public virtual un_roles un_roles { get; set; }
    }
}
