//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_personshistory
    {
        public int id_person { get; set; }
        public string FirstName { get; set; }
        public string SirName { get; set; }
        public string LastName { get; set; }
        public string FirstNameLatin { get; set; }
        public string SirNameLatin { get; set; }
        public string LastNameLatin { get; set; }
        public int id_gender { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_module { get; set; }
        public int id_personParent { get; set; }
    
        public virtual un_gender un_gender { get; set; }
        public virtual un_persons un_persons { get; set; }
    }
}
