//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_professionalareas
    {
        public un_professionalareas()
        {
            this.un_professionalgroups = new HashSet<un_professionalgroups>();
        }
    
        public int id_professionalArea { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public Nullable<int> CodeMon { get; set; }
    
        public virtual ICollection<un_professionalgroups> un_professionalgroups { get; set; }
    }
}
