//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_personlanguages
    {
        public int id_personLanguage { get; set; }
        public int id_person { get; set; }
        public int id_language { get; set; }
        public Nullable<int> id_languageLevel { get; set; }
    
        public virtual un_languagelevels un_languagelevels { get; set; }
        public virtual un_languages un_languages { get; set; }
        public virtual un_persons un_persons { get; set; }
    }
}
