//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_professionalgroups
    {
        public un_professionalgroups()
        {
            this.ph_assignmentshistory = new HashSet<ph_assignmentshistory>();
        }
    
        public int id_professionalGroup { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public string ProfessionalArea { get; set; }
        public Nullable<int> id_professionalArea { get; set; }
    
        public virtual ICollection<ph_assignmentshistory> ph_assignmentshistory { get; set; }
        public virtual un_professionalareas un_professionalareas { get; set; }
    }
}
