//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_roles
    {
        public un_roles()
        {
            this.un_positions = new HashSet<un_positions>();
        }
    
        public int id_role { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<un_positions> un_positions { get; set; }
    }
}
