//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_regions
    {
        public un_regions()
        {
            this.un_municipalities = new HashSet<un_municipalities>();
        }
    
        public int id_Region { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<un_municipalities> un_municipalities { get; set; }
    }
}
