//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_specialitytypes
    {
        public un_specialitytypes()
        {
            this.un_specialities = new HashSet<un_specialities>();
        }
    
        public int id_specialityType { get; set; }
        public string Name { get; set; }
        public string NameLatin { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> MonCode { get; set; }
        public Nullable<int> id_professionalArea { get; set; }
    
        public virtual ICollection<un_specialities> un_specialities { get; set; }
    }
}
