//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_specialities
    {
        public un_specialities()
        {
            this.ph_assignments = new HashSet<ph_assignments>();
        }
    
        public int id_speciality { get; set; }
        public int id_department { get; set; }
        public int id_specialityType { get; set; }
        public Nullable<System.DateTime> AccreditatedFrom { get; set; }
        public Nullable<System.DateTime> AccreditatedTo { get; set; }
        public Nullable<bool> IsAccreditated { get; set; }
        public Nullable<int> id_userEdit { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> id_module { get; set; }
    
        public virtual ICollection<ph_assignments> ph_assignments { get; set; }
        public virtual un_departments un_departments { get; set; }
        public virtual un_specialitytypes un_specialitytypes { get; set; }
    }
}
