//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_treerevisions
    {
        public un_treerevisions()
        {
            this.un_departmenttree = new HashSet<un_departmenttree>();
        }
    
        public int id_treeRevision { get; set; }
        public Nullable<int> RevisionNumber { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual ICollection<un_departmenttree> un_departmenttree { get; set; }
    }
}
