//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIS_TRY_02.Data_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_users
    {
        public un_users()
        {
            this.un_userrights = new HashSet<un_userrights>();
        }
    
        public int id_user { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public int id_person { get; set; }
    
        public virtual un_persons un_persons { get; set; }
        public virtual ICollection<un_userrights> un_userrights { get; set; }
    }
}
